name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Build Server
        run: | 
          npm ci 
          npm run build
      - name: Check out UI
        uses: actions/checkout@master
        with:
          path: ui/
          repository: SnurfDev/spaste-server
          token: ${{ secrets.PAT }}
      - name: Build UI
        working-directory: ./ui
        run: |
          npm ci
          npm run build
          mkdir ../dist/public
          cp -r ./dist/* ../dist/public/
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: static_build
          path: ./dist/
        
